### ISSUE TITLE
Browser window opening 2x when running a test

### ISSUE THREAD

**Issue by brazabr** [klassijs/klassi-js#12]
I cloned your library for evaluation and found this problem:

When I start the test `node index.js -d -t @search` the browser window opens twice and the selenium just uses the second one.

I found out this is due to having 2 hooks ([one Before](https://github.com/larryg01/klassi-cucumber-js/blob/development/runtime/world.js#L294) and [another BeforeAll](https://github.com/larryg01/klassi-cucumber-js/blob/development/runtime/world.js#L246)) calling getDriverInstance() and the Before is not checking if it is already instantiated.

**Comment by larryg01** [comment]
@collabratech After removing the Before hook, did you run the @search again using more that one search variable
