### ISSUE TITLE
Proxy defined is not allowing to access HTTP pages

### ISSUE THREAD

**Issue by JohnTorvik** [klassijs/klassi-js#18]
The [object`s](https://github.com/larryg01/klassi-cucumber-js/blob/2ce3fc6422c45ffd688c03c5d1f027c91ee70ce9/runtime/firefoxDriver.js#L18) content present in the chromeDriver.js and firefoxDriver.js does not allows to access HTTP pages.

**Comment by larryg01** [comment]
Thanks for your work on this forgot to refactor for NONE VPN based environments
