### ISSUE TITLE
how to run parallel test

### ISSUE THREAD

**Issue by shabfactor** [klassijs/klassi-js#23]
i tried 

> desiredCapabilities: {
>       browserName: 'chrome',
>       maxSessions: 2,
>       javascriptEnabled: true,
>       acceptSslCerts: true,
>       shardTestFiles: true,
>       browserConnectionEnabled : true,      
>       chromeOptions: {
>         // args: ['--headless',
>         // ],
>       },

but it does not started multiple sessions of chrome.

**Comment by larryg01** [comment]
are you referring to doing a parallel test run? if not i would need more information as to what exactly do you mean

**Comment by shabfactor** [comment]
@larryg01  thanks for coming back to me, yes i am referring to doing a parallel test run, basically i have multiple features, and want to run them in parallel so one feature runs on one session and other on different session but parallel, but same browser. Thanks

**Comment by shabfactor** [comment]
@larryg01  waiting for your reply.another thing is i am using your klaasi-cucumber-js and it fires a browser even for api tests, which i don't want.

**Comment by larryg01** [comment]
To run parallel test you will need to set up a Selenium GRID or run your test via browserstack / sourcelabs etc
