### ISSUE TITLE
running on selenium grid

### ISSUE THREAD

**Issue by shabfactor** [klassijs/klassi-js#24]
@larryg01  sorry to bother you but if you can tell me how to run this on selenium grid, it will be of great help.I have setup hub on machine now getting current error.

```
Unable to create new service: ChromeDriverService
       Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:32:19.891Z'
       System info: host: 'shaibals-MacBook-Pro.local', ip: 'fd5c:339:88a3:b100:c9f3:beab:39fe:d667', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.6', java.version: '1.8.0_131'
       Driver info: driver.version: unknown

```

**Comment by larryg01** [comment]
From the little information you supplied it looks like your grid is not setup properly.
you should be able to start and run new services from within the browser manually, try that and let me know how you get on

**Comment by larryg01** [comment]
Closing for lack of response
