### ISSUE TITLE
Browserstack

### ISSUE THREAD

**Issue by rhowk** [klassijs/klassi-js#25]
Unable to connect to browserstack
` @search
  Scenario Outline: User inputs some search data
    ✖ failed
      Error: connect ECONNREFUSED 207.254.8.2:4444
          at new RuntimeError (/Users/rhowk1271/Sites/time/testing/ent-testing2/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:143:12)
          at Request._callback (/Users/rhowk1271/Sites/time/testing/ent-testing2/node_modules/webdriverio/build/lib/utils/RequestHandler.js:330:43)
          at self.callback (/Users/rhowk1271/Sites/time/testing/ent-testing2/node_modules/request/request.js:185:22)
`
I've tested the username and key on https://github.com/browserstack/cucumber-js-browserstack and it makes the connection successfully so I think I've got that bit right.
node index.js -d -t @search -w browserstack -x win10-chrome 
is the command I am using, sussed out that I needed to include -x win10-chrome 
node index.js -d -t @search
works ok except for some GraphicsMagick/ImageMagick: errors which I don't care about right now. Basically just trying to connect to browserstack and wondering if the api is out of date, or when was the last time you were successful in making a connection to Browser stack? Doing a deeper dive at https://www.browserstack.com/javascript-testing-api but would appreciate any guidance you could give me. Awesome package by the by.

**Comment by larryg01** [comment]
you need to setup an account on browserstack and pass the username and passcode  and also install browserstack local on your local PC.
As for graphicmagick you also have to download and install that locally.... its used for taking the images for css testing comparison (i.e. page responsiveness)

**Comment by rhowk** [comment]
Fixed this particular problem, was running node 10.1 reverted to 8.6 and changed
"browserstack.local": 
to false and it connects and runs the basic tests.
