### ISSUE TITLE
[suggestion] Screanshots after faill

### ISSUE THREAD

**Issue by zalewskigrzegorz** [klassijs/klassi-js#3]
There is any ability to save a screenshot and attach it to report after the test fails?

**Comment by larryg01** [comment]
That feature already exist, have a look at the last function in the world file

**Comment by larryg01** [comment]
That feature already exist, have a look at the last function in the world file

**Comment by zalewskigrzegorz** [comment]
I see this line in After function and attachment are added to scenario object but unfortunately, I don't see any image in output Html file

**Comment by martinwoit** [comment]
```
    this.After(function (scenario){
      if (scenario.isFailed()) {
          /** add a screenshot to the error report
           */
        driver.saveScreenshot().then(function (screenShot){
          scenario.attach(new Buffer(screenShot, 'base64'), 'image/png');
        })
      }
      return driver.end()
    })
```
should do the trick!

**Comment by zalewskigrzegorz** [comment]
Technically it works but Browser don't close after scenario fail

**Comment by larryg01** [comment]
What browser are you using? because the line 
return driver.end() 
should always closes the browser
But i will have a comprehensive look and then post an update

Thanks for the comment

**Comment by zalewskigrzegorz** [comment]
It works incidentally I added the return before driver.saveScreenshot.
When you plan add @martinwoit  fix to world.js?

**Comment by larryg01** [comment]
Yes i will, i have updated the code, will be doing an update of the whole project soon
