### ISSUE TITLE
Async Problem / Race Condition  in Image Comparison

### ISSUE THREAD

**Issue by janrenz** [klassijs/klassi-js#37]
Hi,

thanks for this nice work. We found an issue when Image Comparison took too long in imageComparision.js.

This is our workaround:
```
     *
     * @param result
     * @returns {Promise<void>}
     */
    this.value = async function () {
      filename = await file_name;
      
      const resultPathNegative = `${resultDirNegative}${filename}`;
      const resultPathPositive = `${resultDirPositive}${filename}`;
      //await driver.pause(500);
      while(typeof result == 'undefined')
        continue;
```

But maybe you can come up with a nice solution.

**Comment by larryg01** [comment]
Thank you very much for your input and I will definitely look into it, you never know i may just use your workaround.
Thanks again

**Comment by larryg01** [comment]
Thank you very much for your input and I will definitely look into it, you never know i may just use your workaround.
Thanks again

**Comment by larryg01** [comment]
I closed it by mistake lol

**Comment by janrenz** [comment]
Does this make sense:
```
    resemble(baselinePath)
      .compareTo(resultPathPositive)
      .ignoreAntialiasing()
      .ignoreColors()
      .onComplete(async function (res) {
        result = await res;
      });
```
As far as I see, res is not a promise but a object ...

**Comment by larryg01** [comment]
Hi Jan,

 

I am not following your comment at all.

On completion I want to capture the result and then use it at a later time.

I am more than happy if you have a better way to do it, please share.

 

Larry

**Comment by janrenz** [comment]
You using 
```await res```
but as res is not a Promise but an object here, this will always resolve immediately.
It would be nice if we wait for res to be defined before assigning this to result...

**Comment by larryg01** [comment]
Ok I follow what you are saying but my choice of words i.e res and result maybe wrong

I think I will just have to change ‘await res’ to ‘return res’ as what am doing is recording the res and then using it later in a following function

What do you think about that approach

**Comment by janrenz** [comment]
I finally solved it by this part of code:
```
   while(typeof result == 'undefined'){
        await driver.pause(100);
        continue;
      }
```

**Comment by larryg01** [comment]
That solution will replace  which bit of code?
is that still in relation to the:  result = await res;
