### ISSUE TITLE
Update WebdriverIO to v5

### ISSUE THREAD

**Issue by christian-bromann** [klassijs/klassi-js#38]
Currently the WebdriverIO version is pinned to `^4.12.0`. I highly recommend to update to v5. It is pretty stable and sees growing adaption. It comes with a ton of bug fixes and improvements compared to v4.

**Comment by larryg01** [comment]
I have started to do that but will have to wait a bit for full upgrade as i am using webderiverio in standalone mode with cucumber and as you know your plugin is not quite ready as yet.

**Comment by christian-bromann** [comment]
> standalone mode with cucumber and as you know your plugin is not quite ready as yet.

If you use webdriverio in standalone mode you don't need to wait for the cucumber-framework adapter to be ported. This adapter is only used with the wdio testrunner

**Comment by larryg01** [comment]
Ok thanks for that, so that means i will have my upgrade completed sooner rather than later as i have already started but its a after the day job thing so hoping to finish as soon as
