### ISSUE TITLE
Credit link to original source selenium-cucumber-js has been removed

### ISSUE THREAD

**Issue by john-doherty** [klassijs/klassi-js#4]
The credit section within the README that linked back to the project that provided 98% of this code has been removed https://github.com/john-doherty/selenium-cucumber-js. 

As this project was copied rather than forked, credit in the README would be appreciated. This condition is specified in the ISC License of the original project (https://github.com/john-doherty/selenium-cucumber-js/blob/master/LICENSE):

**Comment by larryg01** [comment]
It was removed in error, if you looked at the NPM you will see that its still there and was never removed.
