### ISSUE TITLE
Feature: Hide Elements before taking screenshot

### ISSUE THREAD

**Issue by janrenz** [klassijs/klassi-js#44]
Hi,

I added some functions so you can hide elements from the visual regression testing that contains dynamic content:

https://github.com/schul-cloud/integration-tests/pull/10/files

Do you want me to make this PR against this repo as well?

Jan

**Comment by larryg01** [comment]
Hi,

I have upgraded the framework to use version 5 of webdriverio. so lots of changes tomthe way the commands are passed, have a look .
what you can do is send me the files and i will add the new functions and give you the credit in the git commit

Larry

**Comment by janrenz** [comment]
Ok, will have a look based on the v5 version

**Comment by larryg01** [comment]
Jan,

Go ahead and send the PR

**Comment by janrenz** [comment]
https://github.com/larryg01/klassi-js/pull/45

**Comment by janrenz** [comment]
You may need to adopt the TypeScript docs and recreate the global.ts file, I am not so familiar with TS yet.

**Comment by larryg01** [comment]
will do on my next update
