### ISSUE TITLE
helper-function "getElementText" not working anymore

### ISSUE THREAD

**Issue by MxmRz** [klassijs/klassi-js#46]
I just updated to the newest version of the klassi-js repo and therefore to the newest version of webdriverio. Now the "getElementText" function does not work anymore and throws this error: 
```
Then a pupil should see the dashboard
    × failed
      TypeError: driver.waitForExist is not a function
          at Object.getElementText (C:\Users\Job\Desktop\integration-tests\runtime\helpers.js:298:19)
```

I tried fixing the function but I could not find the solution. The changelog of webdriverio does not mention the waitForExist function being renamed or deleted.

**Comment by larryg01** [comment]
Yes some of the helpers may not work because they have changed the way v5 works, i will spend a bit of time and refactor all the helpers so they work again, in the mean time give this a try and let me know
 
getElementText: async function (selector) {
    await driver.$(selector).waitForExist(DELAY_10_SECOND);
    await driver.pause(DELAY_3_SECOND);
    let text = await driver.$(selector).getText();
    return text;
  },

**Comment by MxmRz** [comment]
I actually tried a similiar approach (like your example), that did not work. Your approach (just as my approach) lead to pretty much the same error: 

```
Then a pupil should see the dashboard
    × failed
      TypeError: driver.$(...).waitForExist is not a function
          at Object.getElementText (C:\Users\Job\Desktop\integration-tests\runtime\helpers.js:298:30)
```

The error is referencing this line: 
`await driver.$(selector).waitForExist(DELAY_10_SECOND);`

**Comment by janrenz** [comment]
See https://webdriver.io/docs/api/element/waitForExist.html

**Comment by MxmRz** [comment]
Fixed with the following: 

``` 
let elem = await driver.$(selector);
await elem.waitForExist(DELAY_10_SECOND);
let text = await elem.getText();
return text;
```

**Comment by larryg01** [comment]
Thanks for that and yes in v5 you cant really join commands as you did in v4
