### ISSUE TITLE
Setting fixed resolution for local tests

### ISSUE THREAD

**Issue by MxmRz** [klassijs/klassi-js#47]
Hey, 

before the update I was able to set a fixed resolution in the chromeDriver.js like this: 
```
driver.then(function () {
    /**
     * sets the browser window size to maximum or a particular size
     */
    // driver.windowHandleMaximize();
    driver.windowHandleSize({width: 1920, height: 1080});
  });
```

This function is now missing. I tried setting the resolution in the capabilities part, but was not able to do so.

**Comment by MxmRz** [comment]
Any idea where I can use this method: https://webdriver.io/docs/api/webdriver.html#setwindowrect 
?

**Comment by janrenz** [comment]
I just saw that Webdriverio latest release (3 hours ago) features a method that can be used within tests.
https://github.com/webdriverio/webdriverio/commit/b7ab39f46d896a6ac671080e11f420dd56ea08d2

**Comment by janrenz** [comment]
I successfully used this method at the end of chrome driver:
```
await driver.setWindowSize(600, 800);
```
be sure to have the latest version of webdriverIO installed

**Comment by larryg01** [comment]
This issue has been rectified with PR #48
