### ISSUE TITLE
Debugging 

### ISSUE THREAD

**Issue by jcorbett000** [klassijs/klassi-js#6]
Hello. Im using the framework to demo a few testing ideas, and tried to follow the debugging steps by adding *debugger;* to my code but the test never gets in to the REPL. Is this still the recommended method to debug or should i use *driver.debug()* with mocha timeouts? Thanks

**Comment by larryg01** [comment]
Hi @jcorbett000 sorry for not getting back to your sooner, but if you are using mocha in your scripts then yes you should use driver.debug(), if not then the debugging tool inside your IDE will work.

**Comment by jcorbett000** [comment]
Thanks. I will give this a try. Cheers!
