### ISSUE TITLE
run klassi

### ISSUE THREAD

**Issue by nesrinezouariseryce** [klassijs/klassi-js#81]
hello,

i just start leaning Webdriverio and found this complete library wonderful .
i had clone repo and run npm install , iwould like to run api test so i process with npm test  or node index.js --tags @api but the two commands fails any how to use blog?

**Comment by larryg01** [comment]
can you tell me how you are running the command, are you doing so from inside the project folder?
can you share screen shot of your terminal window?

**Comment by nesrinezouariseryce** [comment]
Hello ,
i run npm i 
npm test
npm dev 
from inside project via VS or via Windows Commande

for second step i installed yarn 
i run yarn install 
i update chromedriver to 95 .. i thing issue come from here , i changed firefox as browser i have everytime chrome launch with blanck page ( TCP error ) 

bellow error
`C:\Users\NesrineZOUARI\source\klassi-js>npm test

> klassi-js@4.0.3 test
> node index.js --disableReport --tags @api

@api @uattest
Feature: The API feature/functionality # features\getMethod.feature:2

  @api @uattest
  Scenario: Recording API response time, status and content # features\getMethod.feature:4
    × failed
      Error: connect ECONNREFUSED ::1:60577
          at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
    Given That I make a GET call to an endPoint
    - skipped
    Then I expect status code of '200'
    - skipped
    Then I return the content of the API
    - skipped
    × failed`

**Comment by larryg01** [comment]
C:\Users\NesrineZOUARI\source\klassi-js>yarn install
C:\Users\NesrineZOUARI\source\klassi-js>yarn run test

**Comment by nesrinezouariseryce** [comment]
C:\Users\NesrineZOUARI\source\klassi-js>yarn run dev
yarn run v1.22.17
$ node index.js --disableReport --tags @search
@uattest
Feature: Searching for apps with duckduckgo # features\duckDuckGo-search.feature:2

  As an internet user
  In order to find out more about certain user apps
  I want to be able to search for information about the required apps

  @uattest @search
  Scenario Outline: User inputs some search data # features\duckDuckGo-search.feature:11
    × failed
      Error: connect ECONNREFUSED ::1:59624
          at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16)
    Given The user arrives on the duckduckgo search page

**Comment by nesrinezouariseryce** [comment]
thanks larry for hel , it was due to lack of installation of selenium through yarn add command , we should use npm install instead
